language: php

php:
  - "5.6"
  - "7.0"

install:
  - composer self-update
  - sudo apt-get install php-phpdbg

before_script:
  - phpenv config-rm xdebug.ini
  - mv .env.travis .env
  - mv travis.phpunit.xml phpunit.xml
  - mysql -e 'create database test_timegrid;'
  - composer install --dev --no-interaction
  - php artisan config:clear
  - php artisan migrate
  - php artisan db:seed
  - php artisan geoip:update
  - php artisan config:cache

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - ./travis-codeclimate-report.sh
